# Generated by Django 5.0.3 on 2024-03-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superusuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
